language: python
python:
  - 2.6
  - 2.7
env:
  # test the standalone functionality
  - DJANGO=1.3.7 CUSTOM_USER_MODEL=0 MODE=standalone REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
  - DJANGO=1.4.5 CUSTOM_USER_MODEL=0 MODE=standalone REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
  - DJANGO=1.5.1 CUSTOM_USER_MODEL=0 MODE=standalone REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
  - DJANGO=1.5.1 CUSTOM_USER_MODEL=1 MODE=standalone REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
  # test django registration integration
  - DJANGO=1.4.5 CUSTOM_USER_MODEL=0 MODE=django_registration REQUIREMENTS=django_registration SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
  # userena currently doesn't support testing :(
  - DJANGO=1.5.1 CUSTOM_USER_MODEL=0 MODE=userena REQUIREMENTS=userena SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook
postgres:
  adapter: sqlite3
  database: django_fb_test
install:
  - pip install pep8 --use-mirrors
  - pip install coverage
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - python setup.py install
  - pip install -r facebook_example/requirements/$REQUIREMENTS.txt --use-mirrors -I
  - pip install -q Django==$DJANGO --use-mirrors -I
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 django_facebook open_facebook"
#  - pyflakes -x W src
script:
  - pip install -e .
  - cd facebook_example
  - coverage run manage.py test $TESTS --settings=$SETTINGS -v2
  - coverage report